import requests

def download_favicon(url, save_name):
    # 构造 favicon 的 URL（假设直接访问 /favicon.ico）
    favicon_url = url.rstrip("/") + "/favicon.ico"
    response = requests.get(favicon_url)
    
    if response.status_code == 200:
        _path = save_name + ".ico"
        with open(_path, "wb") as f:
            f.write(response.content)
        # print(f"Favicon downloaded: {_path}")
    else:
        print(f"Failed to fetch favicon for {url}")

# download_favicon( "https://stackoverflow.com",  "Stack_Overflow")
# download_favicon( "https://www.reddit.com",  "Reddit")
# download_favicon( "https://www.youtube.com",  "YouTube")
# download_favicon( "https://music.youtube.com",  "YouTube_Music")
# download_favicon( "https://www.google.com",  "Google")
# download_favicon( "https://drive.google.com",  "Google_Drive")
# download_favicon( "https://mail.google.com",  "Google_mail" )
# download_favicon( "https://github.com",  "GitHub")
# download_favicon( "https://www.netflix.com",  "Netflix")
# download_favicon( "https://v.qq.com",  "vqq")
# download_favicon( "https://www.iqiyi.com",  "iquiyi")
# download_favicon( "https://www.taobao.com",  "taobao")
# download_favicon( "https://www.tmall.com",  "tmall")
# download_favicon( "https://www.jd.com",  "jd")
# download_favicon( "https://www.bilibili.com",  "Bilibili")
# download_favicon( "https://www.zhihu.com",  "zhihu")
# download_favicon( "https://x.com",  "X" )
# download_favicon( "https://www.icloud.com",  "iCloud")
# download_favicon( "https://photos.google.com",  "Google_Photos")
download_favicon( "https://docs.google.com",  "Google_Docs" )
download_favicon( "https://sheets.google.com",  "Google_Sheets" )
download_favicon( "https://slides.google.com",  "Google_Slides" )
# download_favicon( "https://www.dropbox.com",  "Dropbox" )
# download_favicon( "https://translate.google.com",  "Google_Translate")
# download_favicon( "https://www.alipay.com/",  "alipay" )
# download_favicon( "https://chat.openai.com/",  "ChatGPT")
# download_favicon( "https://gemini.google.com/",  "Gemini" )
# download_favicon( "https://www.immigration.govt.nz/",  "NZ_Immigration")
# download_favicon( "https://www.aut.ac.nz/",  "AUT" )
# download_favicon( "https://aut.communityforce.com/Funds/Search.aspx",  "AUT_Community" )
# download_favicon( "https://www.unilodge.co.nz/",  "UniLodge" )
# download_favicon( "https://www.nuist.edu.cn/",  "NUIST" )
# download_favicon( "https://www.instagram.com/",  "Instagram" )
# download_favicon( "https://www.amytele.net/clientarea.php",  "AmyTele")
# download_favicon( "https://salttiger.com/",  "Salt_Tiger")
# download_favicon( "https://www.python.org",  "Python")
# download_favicon( "https://developer.mozilla.org",  "MDN")
# download_favicon( "https://quaternions.online/",  "Quaternions_Online")
# download_favicon( "https://matrixcalc.org/en/",  "Matrix_Calculator" )
# download_favicon( "https://www.andre-gaschler.com/rotationconverter/",  "Rotation_Converter" )
# download_favicon( "https://www.desmos.com",  "Desmos" )
# download_favicon( "https://mathworld.wolfram.com/",  "Wolfram_MathWorld")
# download_favicon( "https://jsonformatter.curiousconcept.com/#",  "JSON_Formatter" )
# download_favicon( "https://www.gamedeveloper.com/",  "Game_Developer")
# download_favicon( "https://cowboyprogramming.com/",  "Cowboy_Programming")
# download_favicon( "https://badgen.net/",  "Badgen")
# download_favicon( "https://www.figma.com/",  "Figma")
# download_favicon( "https://www.canva.com/",  "Canva")
# download_favicon( "https://www.adobe.com/express/",  "Adobe_Express")
# download_favicon( "https://www.photopea.com/",  "Photopea")
# download_favicon( "https://www.remove.bg/",  "Remove_BG")
# download_favicon( "https://www.iloveimg.com/",  "iLoveIMG")
# download_favicon( "https://www.smallpdf.com/",  "SmallPDF")
# download_favicon( "https://www.overleaf.com/",  "Overleaf")
# download_favicon( "https://www.markdownguide.org/",  "Markdown_Guide")
# download_favicon( "https://www.tablesgenerator.com/",  "Tables_Generator")
# download_favicon( "https://www.latex-project.org/",  "LaTeX_Project")
# download_favicon( "https://www.typing.com/",  "Typing_com")


# download_favicon( "https://www.speedtest.net/",  "Speedtest")
# download_favicon( "https://www.whatismybrowser.com/",  "WhatIsMyBrowser")
# download_favicon( "https://www.browserstack.com/",  "BrowserStack")
# download_favicon( "https://www.crossbrowsertesting.com/",  "CrossBrowserTesting")

# download_favicon( "https://www.selenium.dev/",  "Selenium")
# download_favicon( "https://www.postman.com/",  "Postman")
# download_favicon( "https://www.heroku.com/",  "Heroku")
# download_favicon( "https://www.netlify.com/",  "Netlify")
# download_favicon( "https://vercel.com/",  "Vercel")
# download_favicon( "https://www.digitalocean.com/",  "DigitalOcean")
# download_favicon( "https://aws.amazon.com/",  "AWS")
# download_favicon( "https://azure.microsoft.com/",  "Azure")
# download_favicon( "https://cloud.google.com/",  "Google_Cloud")
# download_favicon( "https://www.mongodb.com/",  "MongoDB")
# download_favicon( "https://www.postgresql.org/",  "PostgreSQL")
# download_favicon( "https://www.mysql.com/",  "MySQL")
# download_favicon( "https://redis.io/",  "Redis")
# download_favicon( "https://www.sqlite.org/",  "SQLite")
# download_favicon( "https://www.docker.com/",  "Docker")
# download_favicon( "https://kubernetes.io/",  "Kubernetes")
# download_favicon( "https://www.nginx.com/",  "NGINX")
# download_favicon( "https://www.apache.org/",  "Apache_HTTP_Server")
# download_favicon( "https://www.cloudflare.com/",  "Cloudflare")
# download_favicon( "https://www.fastly.com/",  "Fastly")
